# Generated by Django 4.1 on 2023-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(verbose_name="Internal Code")),
                ("price", models.FloatField(verbose_name="Price")),
                ("wPrice", models.IntegerField(verbose_name="wholesaler's price")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="products/defaultProduct.png",
                        null=True,
                        upload_to="products",
                        verbose_name="Image",
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="Stock")),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateField(auto_now_add=True, verbose_name="Updated"),
                ),
                ("category", models.ManyToManyField(to="products.category")),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.brand"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Products",
                "verbose_name_plural": "Productss",
            },
        ),
    ]
