# Generated by Django 4.2 on 2023-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_products_brand_alter_products_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
