# Generated by Django 4.2 on 2023-05-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_products_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.provider",
            ),
        ),
    ]
