# Generated by Django 4.2 on 2023-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='wPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name="wholesaler's price"),
        ),
    ]
