# Generated by Django 4.2 on 2023-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En Preparacion', 'En Preparacion'), ('Orden Preparada', 'Orden Preparada'), ('Enviado', 'Enviado')], max_length=50, verbose_name='Order Order')),
                ('payment_status', models.CharField(choices=[('No Pagado', 'No Pagado'), ('Pago Recibido', 'Pago Recibido')], max_length=50, verbose_name='Estado del pago')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('items', models.ManyToManyField(to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orderss',
            },
        ),
    ]
