# Generated by Django 4.2 on 2023-09-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En Preparacion', 'En Preparacion'), ('Orden Preparada', 'Orden Preparada'), ('Enviado', 'Enviado')], default='No Iniciado', max_length=50, verbose_name='Order Order'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('No Pagado', 'No Pagado'), ('Pago Recibido', 'Pago Recibido')], default='No Pagado', max_length=50, verbose_name='Estado del pago'),
        ),
    ]
