# Generated by Django 4.2 on 2023-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_boss',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_employe',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('boos', 'boos'), ('employe', 'employe')], default='client', max_length=50, verbose_name='Role'),
        ),
    ]
