# Generated by Django 4.2 on 2023-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company')),
                ('cuil', models.IntegerField(verbose_name='CUIT')),
                ('cuit', models.IntegerField(verbose_name='CUIL')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('image', models.ImageField(default='logos/LogoDefault.png', upload_to='logos', verbose_name='Image')),
                ('phone', models.IntegerField(verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
    ]
