# Generated by Django 4.2 on 2023-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.FloatField(default=0.0)),
                ('products', models.ManyToManyField(to='products.products')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Saless',
            },
        ),
    ]
